server:
  port: 8086
spring:
  application:
    name: consumer-service
  cloud:
    nacos:
      server-addr: localhost:8848

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
